export enum ModuleType {
	BIQUAD_FILTER = 'MODULE_BIQUAD_FILTER',
	OSCILLATOR = 'MODULE_OSCILLATOR',
	GAIN = 'MODULE_GAIN',
	IIR_FILTER = 'MODULE_IIR_FILTER',
	DISTORTION = 'MODULE_DISTORTION',
	DELAY = 'MODULE_DELAY',
	PANNER = 'MODULE_PANNER',
	COMPLEX = 'MODULE_COMPLEX',
	REVERB = 'MODULE_REVERB'
  }