services:
  frontend:
    build: ./app
    ports:
      - "80:80"
    depends_on:
      - backend
    restart: "unless-stopped"

  backend:
    build: ./api
    ports:
      - "8000:8000"
    restart: "unless-stopped"
