FROM node:alpine AS base


FROM base AS builder

WORKDIR /usr/src
COPY lib/shared/ ./lib/shared/
COPY api/ ./api/

WORKDIR /usr/src/lib/shared
RUN npm ci

WORKDIR /usr/src/api
RUN npm ci
COPY .env* .
COPY api/.env* .
RUN npm run build:prod


FROM base AS server

RUN mkdir -p /usr/src
WORKDIR /usr/src
COPY --from=builder /usr/src/api/node_modules /usr/src/node_modules
COPY --from=builder /usr/src/api/build /usr/src

EXPOSE 3000

WORKDIR /usr/src
CMD [ "node", "./index.js" ]