[unix_http_server]
file=/tmp/supervisor.sock
chmod=0755 

[supervisord]
logfile=/dev/logfile

[program:api]
command=node ./index.js
directory=/usr/src/api
autorestart=false
stopasgroup=true
killasgroup=true
stdout_logfile=/dev/stdout
stderr_logfile=/dev/stderr

[program:app]
command=nginx -g 'daemon off;'
directory=/usr/share/nginx/html
autorestart=false
stopasgroup=true
killasgroup=true
stdout_logfile=/dev/stdout
stderr_logfile=/dev/stderr