[supervisord]
nodaemon=true
logfile=/dev/null

[program:api]
command=node ./index.js
directory=/app
autorestart=false
stopasgroup=true
killasgroup=true
stdout_logfile=/dev/stdout
stderr_logfile=/dev/stderr

[program:app]
command=nginx -g 'daemon off;'
directory=/usr/share/nginx/html
autorestart=false
stopasgroup=true
killasgroup=true
stdout_logfile=/dev/stdout
stderr_logfile=/dev/stderr
