export enum IOType {
  SOURCE = 'IO_SOURCE',
  DESTINATION = 'IO_DESTINATION',
  MOD = 'IO_MOD',
  PARAM = 'PARAM_OPTION',
  BOOLEAN = 'PARAM_BOOLEAN',
  A_RATE = 'PARAM_A_RATE',
  K_RATE = 'PARAM_K_RATE',
  READONLY = 'PARAM_READONLY'
}