import generate from "server-name-gen";

export const randomName = (customNoun?: string) => {
  if (customNoun) {
    const randomName = generate({ words: 3 }).raw;
    randomName[2] = customNoun;
    return randomName.join("-");
  } else {
    return generate({
      words: 3,
      alliterative: true,
      blocklist: ["slave"],
      adjectives: [
        "abnormal",
        "angular",
        "appreciative",
        "artistic",
        "artsy",
        "attentive",
        "balanced",
        "brave",
        "bulky",
        "confident",
        "creative",
        "dedicated",
        "depressed",
        "analog",
        "modular",
        "ecstatic",
        "extraordinary",
        "fantastic",
        "fat",
        "flexible",
        "flustered",
        "frustrated",
        "generous",
        "hopeful",
        "imaginative",
        "impatient",
        "impressive",
        "indifferent",
        "innovative",
        "inspiring",
        "intelligent",
        "moody",
        "motivated",
        "musical",
        "obvious",
        "optimistic",
        "passionate",
        "brown",
        "patient",
        "perceptive",
        "persistent",
        "pessimistic",
        "playful",
        "plump",
        "practical",
        "radiant",
        "reliable",
        "resourceful",
        "satisfied",
        "shining",
        "slender",
        "spontaneous",
        "square",
        "stressed",
        "thick",
        "thrilling",
        "trustworthy",
        "ugly",
        "understanding",
        "versatile",
        "vibrant",
        "worn",
      ],
      nouns: [
        "asteroid",
        "automaton",
        "bend",
        "blackhole",
        "boson",
        "buffer",
        "clipper",
        "comet",
        "crusher",
        "decimator",
        "electron",
        "elevator",
        "energy",
        "expander",
        "fader",
        "fermion",
        "function",
        "galaxy",
        "gravity",
        "horizon",
        "jitter",
        "message",
        "meteor",
        "meteorite",
        "method",
        "nebula",
        "neutrino",
        "neutron",
        "object",
        "photon",
        "planet",
        "process",
        "proton",
        "pulsar",
        "quark",
        "quasar",
        "response",
        "sample",
        "source",
        "synth",
        "tachyon",
        "trance",
        "trim",
        "universe",
        "wiggle",
        "world",
      ],
    } as any).dashed;
  }
};
