name: Deploy to Staging

on:
  push:
    branches:
      - staging

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Deploy to Staging
        uses: appleboy/ssh-action@v0.1.3
        with:
          host: ${{ secrets.VPS_HOST_STAGING }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.VPS_KEY }}
          port: 22
          script: |
            cd /root/staging.synth.kitchen
            docker build -t placeholder ./frontend/placeholder
            systemctl stop staging.synth.kitchen
            docker run -d placeholder
            git fetch
            git checkout staging
            git pull
            docker stop placeholder
            systemctl start staging.synth.kitchen
